export const AUTHORIZE_CASPIO = "AUTHORIZE_CASPIO";
export const GET_DATA_CASPIO = "REQUEST_DATA_CASPIO";
export const SET_DATA_SOURCE_TABLES_CASPIO = "SET_DATA_SOURCE_TABLES_CASPIO";
export const SET_DATA_SOURCE_VIEWS_CASPIO = "SET_DATA_SOURCE_VIEWS_CASPIO";
export const GET_DATA_SOURCE_COLUMNS_CASPIO = "GET_DATA_SOURCE_COLUMNS_CASPIO";
